FROM ursa-base:0.1 as build-env

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download
COPY . ./
COPY /repos/ /tmp/repos/
RUN rm -rf repos
RUN go build -o /ursa github.com/xralf/ursa/cmd/api-server
#RUN go build -o /chatty github.com/xralf/ursa/cmd/chatty
RUN	go build -o /tmp/demo/demo-pipe-server github.com/xralf/ursa/cmd/pipe/server
RUN	go build -o /tmp/demo/demo-pipe-client github.com/xralf/ursa/cmd/pipe/client
RUN	go build -o /tmp/demo/demo-web-server github.com/xralf/ursa/cmd/demo/web
RUN	go build -o /tmp/demo/demo-console-client github.com/xralf/ursa/cmd/demo/client
RUN	go build -o /tmp/demo/demo-findata-server github.com/xralf/ursa/cmd/finnhub-trades
RUN	go build -o /tmp/demo/syslog github.com/xralf/ursa/cmd/syslog
RUN	go build -o /tmp/demo/throttle github.com/xralf/ursa/cmd/throttle
RUN	go build -o /tmp/demo/generator github.com/xralf/ursa/cmd/datagen

COPY /cmd/demo/web/dashboard.html /tmp/demo
COPY /cmd/demo/web/dashboard-template.html /tmp/demo
COPY /templates /tmp/demo/templates/
COPY ./config.yml /tmp/demo

ENV TZ US/Pacific

EXPOSE 50001-50099 3344

WORKDIR /

CMD [ "./ursa" ]
